/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.example.jooq.tables.LinkTable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkTableRecord extends UpdatableRecordImpl<LinkTableRecord> implements Record3<String, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK_TABLE.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK_TABLE.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 256)
    @NotNull
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>LINK_TABLE.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK_TABLE.LAST_UPDATE</code>.
     */
    @Nullable
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>LINK_TABLE.IS_GITHUB_LINK</code>.
     */
    public void setIsGithubLink(@Nullable Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK_TABLE.IS_GITHUB_LINK</code>.
     */
    @Nullable
    public Boolean getIsGithubLink() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, LocalDateTime, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<String, LocalDateTime, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return LinkTable.LINK_TABLE.URL;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field2() {
        return LinkTable.LINK_TABLE.LAST_UPDATE;
    }

    @Override
    @NotNull
    public Field<Boolean> field3() {
        return LinkTable.LINK_TABLE.IS_GITHUB_LINK;
    }

    @Override
    @NotNull
    public String component1() {
        return getUrl();
    }

    @Override
    @Nullable
    public LocalDateTime component2() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public Boolean component3() {
        return getIsGithubLink();
    }

    @Override
    @NotNull
    public String value1() {
        return getUrl();
    }

    @Override
    @Nullable
    public LocalDateTime value2() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public Boolean value3() {
        return getIsGithubLink();
    }

    @Override
    @NotNull
    public LinkTableRecord value1(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkTableRecord value2(@Nullable LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    @NotNull
    public LinkTableRecord value3(@Nullable Boolean value) {
        setIsGithubLink(value);
        return this;
    }

    @Override
    @NotNull
    public LinkTableRecord values(@NotNull String value1, @Nullable LocalDateTime value2, @Nullable Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkTableRecord
     */
    public LinkTableRecord() {
        super(LinkTable.LINK_TABLE);
    }

    /**
     * Create a detached, initialised LinkTableRecord
     */
    @ConstructorProperties({ "url", "lastUpdate", "isGithubLink" })
    public LinkTableRecord(@NotNull String url, @Nullable LocalDateTime lastUpdate, @Nullable Boolean isGithubLink) {
        super(LinkTable.LINK_TABLE);

        setUrl(url);
        setLastUpdate(lastUpdate);
        setIsGithubLink(isGithubLink);
    }

    /**
     * Create a detached, initialised LinkTableRecord
     */
    public LinkTableRecord(org.example.jooq.tables.pojos.LinkTable value) {
        super(LinkTable.LINK_TABLE);

        if (value != null) {
            setUrl(value.getUrl());
            setLastUpdate(value.getLastUpdate());
            setIsGithubLink(value.getIsGithubLink());
        }
    }
}
