/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.example.jooq.tables.UserLinksTable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLinksTableRecord extends TableRecordImpl<UserLinksTableRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>USER_LINKS_TABLE.USER_CHAT_ID</code>.
     */
    public void setUserChatId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER_LINKS_TABLE.USER_CHAT_ID</code>.
     */
    @Nullable
    public Integer getUserChatId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER_LINKS_TABLE.LINK_URL</code>.
     */
    public void setLinkUrl(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER_LINKS_TABLE.LINK_URL</code>.
     */
    @Size(max = 256)
    @Nullable
    public String getLinkUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return UserLinksTable.USER_LINKS_TABLE.USER_CHAT_ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return UserLinksTable.USER_LINKS_TABLE.LINK_URL;
    }

    @Override
    @Nullable
    public Integer component1() {
        return getUserChatId();
    }

    @Override
    @Nullable
    public String component2() {
        return getLinkUrl();
    }

    @Override
    @Nullable
    public Integer value1() {
        return getUserChatId();
    }

    @Override
    @Nullable
    public String value2() {
        return getLinkUrl();
    }

    @Override
    @NotNull
    public UserLinksTableRecord value1(@Nullable Integer value) {
        setUserChatId(value);
        return this;
    }

    @Override
    @NotNull
    public UserLinksTableRecord value2(@Nullable String value) {
        setLinkUrl(value);
        return this;
    }

    @Override
    @NotNull
    public UserLinksTableRecord values(@Nullable Integer value1, @Nullable String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLinksTableRecord
     */
    public UserLinksTableRecord() {
        super(UserLinksTable.USER_LINKS_TABLE);
    }

    /**
     * Create a detached, initialised UserLinksTableRecord
     */
    @ConstructorProperties({ "userChatId", "linkUrl" })
    public UserLinksTableRecord(@Nullable Integer userChatId, @Nullable String linkUrl) {
        super(UserLinksTable.USER_LINKS_TABLE);

        setUserChatId(userChatId);
        setLinkUrl(linkUrl);
    }

    /**
     * Create a detached, initialised UserLinksTableRecord
     */
    public UserLinksTableRecord(org.example.jooq.tables.pojos.UserLinksTable value) {
        super(UserLinksTable.USER_LINKS_TABLE);

        if (value != null) {
            setUserChatId(value.getUserChatId());
            setLinkUrl(value.getLinkUrl());
        }
    }
}
