version: "3"

services:
  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scrapper
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./scrapper/src/main/resources/db/migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  database:

networks:
  backend:
    driver: bridge