app:
  test: "Benedict Cumberbatch"
  scheduler:
    interval: 120000
  databaseAccessType: jdbc
  rabbitMQConfig:
    queueName: "scrapperQueue"
    exchangeName: "scrapperExchange"
    routingKey: "scrapperRouting"
  useQueue: true

springdoc:
  swagger-ui:
    path: "/swagger-ui"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_updates: true
        order_inserts: true
        format_sql: false

management:
  server:
    port: 9081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

