/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import javax.annotation.processing.Generated;

import org.example.jooq.tables.GithubLinkTable;
import org.example.jooq.tables.LinkTable;
import org.example.jooq.tables.UserLinksTable;
import org.example.jooq.tables.UserTable;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>GITHUB_LINK_TABLE</code>.
     */
    public static final GithubLinkTable GITHUB_LINK_TABLE = GithubLinkTable.GITHUB_LINK_TABLE;

    /**
     * The table <code>LINK_TABLE</code>.
     */
    public static final LinkTable LINK_TABLE = LinkTable.LINK_TABLE;

    /**
     * The table <code>USER_LINKS_TABLE</code>.
     */
    public static final UserLinksTable USER_LINKS_TABLE = UserLinksTable.USER_LINKS_TABLE;

    /**
     * The table <code>USER_TABLE</code>.
     */
    public static final UserTable USER_TABLE = UserTable.USER_TABLE;
}
