app:
  useQueue: true
  test: "Ryan Gosling"
  botConfig:
    name: "TinkoffLinkUpdaterBot"
    token: ${BOT_TOKEN}
  rabbitMQConfig:
    queueName: "scrapperQueue"
    dlqListener: true

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8081

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1