app:
  useQueue: true
  test: "Ryan Gosling"
  botConfig:
    name: "TinkoffLinkUpdaterBot"
    token: ${BOT_TOKEN}
  rabbitMQConfig:
    queueName: "scrapperQueue"

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8081