app:
  useQueue: true
  test: "Ryan Gosling"
  botConfig:
    name: "TinkoffLinkUpdaterBot"
    token: ${BOT_TOKEN}
  rabbitMQConfig:
    queueName: "scrapperQueue"
    dlqListener: true

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8081

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1

management:
  server:
    port: 9082
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: 'info, health, prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
