/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.example.jooq.DefaultSchema;
import org.example.jooq.Keys;
import org.example.jooq.tables.records.GithubLinkTableRecord;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GithubLinkTable extends TableImpl<GithubLinkTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_LINK_TABLE</code>
     */
    public static final GithubLinkTable GITHUB_LINK_TABLE = new GithubLinkTable();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubLinkTableRecord> getRecordType() {
        return GithubLinkTableRecord.class;
    }

    /**
     * The column <code>GITHUB_LINK_TABLE.LINK_URL</code>.
     */
    public final TableField<GithubLinkTableRecord, String> LINK_URL = createField(DSL.name("LINK_URL"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>GITHUB_LINK_TABLE.BRANCH_COUNT</code>.
     */
    public final TableField<GithubLinkTableRecord, Integer> BRANCH_COUNT = createField(DSL.name("BRANCH_COUNT"), SQLDataType.INTEGER.nullable(false), this, "");

    private GithubLinkTable(Name alias, Table<GithubLinkTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubLinkTable(Name alias, Table<GithubLinkTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_LINK_TABLE</code> table reference
     */
    public GithubLinkTable(String alias) {
        this(DSL.name(alias), GITHUB_LINK_TABLE);
    }

    /**
     * Create an aliased <code>GITHUB_LINK_TABLE</code> table reference
     */
    public GithubLinkTable(Name alias) {
        this(alias, GITHUB_LINK_TABLE);
    }

    /**
     * Create a <code>GITHUB_LINK_TABLE</code> table reference
     */
    public GithubLinkTable() {
        this(DSL.name("GITHUB_LINK_TABLE"), null);
    }

    public <O extends Record> GithubLinkTable(Table<O> child, ForeignKey<O, GithubLinkTableRecord> key) {
        super(child, key, GITHUB_LINK_TABLE);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<GithubLinkTableRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubLinkTableRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_BC);
    }

    private transient LinkTable _linkTable;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK_TABLE</code> table.
     */
    public LinkTable linkTable() {
        if (_linkTable == null)
            _linkTable = new LinkTable(this, Keys.CONSTRAINT_BC);

        return _linkTable;
    }

    @Override
    @NotNull
    public GithubLinkTable as(String alias) {
        return new GithubLinkTable(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubLinkTable as(Name alias) {
        return new GithubLinkTable(alias, this);
    }

    @Override
    @NotNull
    public GithubLinkTable as(Table<?> alias) {
        return new GithubLinkTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLinkTable rename(String name) {
        return new GithubLinkTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLinkTable rename(Name name) {
        return new GithubLinkTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLinkTable rename(Table<?> name) {
        return new GithubLinkTable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
