/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private String url;
    private LocalDateTime lastUpdate;
    private Boolean isGithubLink;

    public LinkTable() {}

    public LinkTable(LinkTable value) {
        this.url = value.url;
        this.lastUpdate = value.lastUpdate;
        this.isGithubLink = value.isGithubLink;
    }

    @ConstructorProperties({ "url", "lastUpdate", "isGithubLink" })
    public LinkTable(
        @NotNull String url,
        @Nullable LocalDateTime lastUpdate,
        @Nullable Boolean isGithubLink
    ) {
        this.url = url;
        this.lastUpdate = lastUpdate;
        this.isGithubLink = isGithubLink;
    }

    /**
     * Getter for <code>LINK_TABLE.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 256)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>LINK_TABLE.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>LINK_TABLE.LAST_UPDATE</code>.
     */
    @Nullable
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>LINK_TABLE.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>LINK_TABLE.IS_GITHUB_LINK</code>.
     */
    @Nullable
    public Boolean getIsGithubLink() {
        return this.isGithubLink;
    }

    /**
     * Setter for <code>LINK_TABLE.IS_GITHUB_LINK</code>.
     */
    public void setIsGithubLink(@Nullable Boolean isGithubLink) {
        this.isGithubLink = isGithubLink;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LinkTable other = (LinkTable) obj;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        if (this.isGithubLink == null) {
            if (other.isGithubLink != null)
                return false;
        }
        else if (!this.isGithubLink.equals(other.isGithubLink))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.isGithubLink == null) ? 0 : this.isGithubLink.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinkTable (");

        sb.append(url);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(isGithubLink);

        sb.append(")");
        return sb.toString();
    }
}
