/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer chatId;
    private String username;

    public UserTable() {}

    public UserTable(UserTable value) {
        this.chatId = value.chatId;
        this.username = value.username;
    }

    @ConstructorProperties({ "chatId", "username" })
    public UserTable(
        @NotNull Integer chatId,
        @Nullable String username
    ) {
        this.chatId = chatId;
        this.username = username;
    }

    /**
     * Getter for <code>USER_TABLE.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>USER_TABLE.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>USER_TABLE.USERNAME</code>.
     */
    @Size(max = 32)
    @Nullable
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>USER_TABLE.USERNAME</code>.
     */
    public void setUsername(@Nullable String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserTable other = (UserTable) obj;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserTable (");

        sb.append(chatId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
