/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLinksTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userChatId;
    private String linkUrl;

    public UserLinksTable() {}

    public UserLinksTable(UserLinksTable value) {
        this.userChatId = value.userChatId;
        this.linkUrl = value.linkUrl;
    }

    @ConstructorProperties({ "userChatId", "linkUrl" })
    public UserLinksTable(
        @Nullable Integer userChatId,
        @Nullable String linkUrl
    ) {
        this.userChatId = userChatId;
        this.linkUrl = linkUrl;
    }

    /**
     * Getter for <code>USER_LINKS_TABLE.USER_CHAT_ID</code>.
     */
    @Nullable
    public Integer getUserChatId() {
        return this.userChatId;
    }

    /**
     * Setter for <code>USER_LINKS_TABLE.USER_CHAT_ID</code>.
     */
    public void setUserChatId(@Nullable Integer userChatId) {
        this.userChatId = userChatId;
    }

    /**
     * Getter for <code>USER_LINKS_TABLE.LINK_URL</code>.
     */
    @Size(max = 256)
    @Nullable
    public String getLinkUrl() {
        return this.linkUrl;
    }

    /**
     * Setter for <code>USER_LINKS_TABLE.LINK_URL</code>.
     */
    public void setLinkUrl(@Nullable String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserLinksTable other = (UserLinksTable) obj;
        if (this.userChatId == null) {
            if (other.userChatId != null)
                return false;
        }
        else if (!this.userChatId.equals(other.userChatId))
            return false;
        if (this.linkUrl == null) {
            if (other.linkUrl != null)
                return false;
        }
        else if (!this.linkUrl.equals(other.linkUrl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userChatId == null) ? 0 : this.userChatId.hashCode());
        result = prime * result + ((this.linkUrl == null) ? 0 : this.linkUrl.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserLinksTable (");

        sb.append(userChatId);
        sb.append(", ").append(linkUrl);

        sb.append(")");
        return sb.toString();
    }
}
