name: Bot maven CI

on:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn package -pl bot -am
      
#       - name: Build image
#         run: docker build --build-arg bot_token=${{ secrets.TINKOFF_TELEGRAM_BOT_TOKEN }} -t bot_image bot
      
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: bot
          push: true
          tags: ghcr.io/maksmolchdmitr/tinkofflinkupdater/bot:latest
          build-args: bot_token=${{ secrets.TINKOFF_TELEGRAM_BOT_TOKEN }}
